// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTJsVuW25uU86GYUHQlSyBx9GQ9nm5e8w',
    appId: '1:406745677015:web:e91abb5a2a09b9b0fec492',
    messagingSenderId: '406745677015',
    projectId: 'healing-on',
    authDomain: 'healing-on.firebaseapp.com',
    storageBucket: 'healing-on.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cUGyALOwu9evehwruLRx9ilCg_IB_Zg',
    appId: '1:524336249519:android:54afc1d0e6f21c2af5b25a',
    messagingSenderId: '524336249519',
    projectId: 'k-medical-d6be6',
    storageBucket: 'k-medical-d6be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtSUbo2QCSUB3FO5rsQht7lXx3N0aDnY',
    appId: '1:524336249519:ios:bb5bceee955a2e15f5b25a',
    messagingSenderId: '524336249519',
    projectId: 'k-medical-d6be6',
    storageBucket: 'k-medical-d6be6.firebasestorage.app',
    iosBundleId: 'com.example.healingOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRAojRuJ_Rzw8W_X6Np1LWGPG_HrXXvk',
    appId: '1:406745677015:ios:8c0b7a0038311301fec492',
    messagingSenderId: '406745677015',
    projectId: 'healing-on',
    storageBucket: 'healing-on.appspot.com',
    iosClientId: '406745677015-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com',
    iosBundleId: 'com.example.healingOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTJsVuW25uU86GYUHQlSyBx9GQ9nm5e8w',
    appId: '1:406745677015:web:e8a676d20f159e41fec492',
    messagingSenderId: '406745677015',
    projectId: 'healing-on',
    authDomain: 'healing-on.firebaseapp.com',
    storageBucket: 'healing-on.appspot.com',
  );
}